spring.application.name=url-shortner

#Redis
spring.data.redis.host=redis-19246.c10.us-east-1-3.ec2.cloud.redislabs.com
spring.data.redis.port=19246
spring.data.redis.password=tSkJsQeGQRr0l0CQVfwrdiSQ2ASdvk5p

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener_db
spring.datasource.username=postgres
spring.datasource.password=GoodGod
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.\
  PostgreSQLDialect
